# Generated by Django 3.2.7 on 2021-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatColorsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'B'), ('white', 'W'), ('black & white', 'Bw'), ('red', 'R'), ('red & white', 'Rw'), ('red & black & white', 'Rbw')], max_length=30)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_colors_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CatsColorsInfo',
        ),
        migrations.AlterModelOptions(
            name='cats',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catsstat',
            options={'managed': False},
        ),
    ]
